clc
clear all
close all
%%

ac = aircraft.Aircraft('A320');
ac.planform.plot();

root_cst = ac.airfoils.root.CSTAirfoil;
tip_cst = ac.airfoils.tip.CSTAirfoil;
A_root = [root_cst.A_upper', root_cst.A_lower'];
A_tip = [tip_cst.A_upper', tip_cst.A_lower'];

x = optimize.DesignVector({'lambda_1', ac.lambda_1, 0, 1.25;...
                           'lambda_2', ac.lambda_2, 0.94, 1.25;...
                           'b', ac.b, 0.71, 1.06;...
                           'c_r', ac.c_r, 0.68, 1.15;...
                           'tau', ac.tau, 0.16, 2.5;...
                           'A_root', ac.airfoils.A_root', -2.0, 2.0;...
                           'A_tip', ac.airfoils.A_tip', -2.0, 2.0;...
                           'beta_root', ac.beta_root, 0, 1.7;...
                           'beta_kink', ac.beta_kink, -0.8, 3.2;...
                           'beta_tip', ac.beta_tip, -3.6, 3.6;...
                           % Get these values from first initial run
                           'A_L', ac.A_L, -1.5, 1.5;...
                           'A_M', ac.A_M, -1.5, 1.5;...
                           'W_w', ac.W_w, 0.8, 1.0;...
                           'W_f', ac.W_f, 0.8, 1.0;...
                           'C_d_w', ac.C_d_w, 0.8, 1.0});

assert(all((x.init .* x.vector) == x.init), 'Design Vector Corrupted');
new_vector = ones(length(x.vector), 1);
new_vector(1) = 1.25;
%%
x.vector = new_vector;
% x.update(x.vector * 2); % Updating w/ a new design vector [2, 2, 2, ...]'
% x.fetch_history('normalized', true);

ac.modify(x);